# @see https://jekyllrb.com/docs/configuration/
# @see https://jekyllrb.com/docs/github-pages/

# site settings
title: 'iancampbellstuff'
description: 'The personal developer website of iancampbellstuff.'

# default page layout
defaults:
  - scope:
      path: ''
    values:
      layout: 'default'

# pretty URLs
permalink: pretty

# dark mode
theme: jekyll-theme-slate
